### ISSUE TITLE
数据库结构？

### ISSUE THREAD

**Issue by alanzchen** [tgh980122/CIbbq#1]

**Comment by tyan-boot** [comment]
呃。明天下午回家把数据库结构弄出来…忘记这个了。。

--- Tyan Boot 敬上！ ---

--- 原始邮件 ---

发件人： "Discrete Chan" notifications@github.com
已发： 2015年2月12日 下午6:13
收件人： "tgh980122/CIbbq" CIbbq@noreply.github.com
主题： [CIbbq] 数据库结构？ (#1)

---

Reply to this email directly or view it on GitHub:
https://github.com/tgh980122/CIbbq/issues/1

**Comment by tyan-boot** [comment]
已经修改了readme文件，里面说明了数据库结构
